services:
  mongodb:
    image: 'mongo:latest'
    environment:
      - MONGO_INITDB_DATABASE=skill_trafer
      - MONGO_INITDB_ROOT_PASSWORD=secret
      - MONGO_INITDB_ROOT_USERNAME=root
    ports:
      - '27017'
  postgres:
    image: 'postgres:latest'
    environment:
      - POSTGRES_DB=skill_trafer
      - POSTGRES_PASSWORD=secret
      - POSTGRES_USER=root
    ports:
      - '5432'
  redis:
    image: 'redis:latest'
    ports:
      - '6379'
  adminer:
    image: 'adminer:latest'
    ports:
      - '8080:8080'

#  App:
#    build: .
#    ports:
#      - '3000:3000'
#    depends_on:
#      - mongodb
#      - postgres
#      - redis
#    environment:
#      - 'DATABASE_URL=postgres://myuser:secret@postgres:5432/mydatabase'
#      - 'REDIS_URL=redis://redis:6379'
#      - 'MONGO_URL=mongodb://root:secret@mongodb:27017/mydatabase'
