spring:
  profiles:
    active: dev
  application:
    name: SkillTrafer

  # Database Configuration
  datasource:
    url: jdbc:postgresql://localhost:5432/skill_trafer
    username: root
    password: secret
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        use_sql_comments: true
  data:
    mongodb:
      database: skill_trafer
      host: ${MONGO_HOST:localhost}
      port: ${MONGO_PORT:27017}
      username: ${MONGO_USER}
      password: ${MONGO_PASS}