spring:
  profiles:
    active: dev
  application:
    name: SkillTrafer




# Database Configuration
  datasource:
    url: jdbc:mysql://localhost:3306/skill_trafer
    username: root
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        format_sql: true
        use_sql_comments: true




